/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leads */
        get: operations["get_leads_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_leads__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Lead
         * @description Simulates a lead score based on input.
         *     This endpoint is idempotent and safe to re-trigger.
         */
        post: operations["simulate_lead_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Lead */
        Lead: {
            /** Customer Id */
            customer_id: string;
            /** Name */
            name: string;
            /** Persona Label */
            persona_label: string;
            /** Repayment Capacity Score */
            repayment_capacity_score: number;
            /** Conversion Propensity Score */
            conversion_propensity_score: number;
            /**
             * Tier
             * @enum {string}
             */
            tier: "Hot" | "Warm" | "Cold";
            /** Thin File */
            thin_file: boolean;
            /**
             * Recommended Product
             * @enum {string}
             */
            recommended_product: "Personal Loan" | "Home Loan" | "Mortgage Loan" | "Auto Loan";
            /** Eligible Loan Amount */
            eligible_loan_amount: number;
            /** Top Factors */
            top_factors: components["schemas"]["TopFactor"][];
            /** Explanation Text */
            explanation_text: string;
        };
        /** Metrics */
        Metrics: {
            /** Baseline Conversion Rate */
            baseline_conversion_rate: number;
            /** Prospectiq Conversion Rate */
            prospectiq_conversion_rate: number;
            /** Conversion Lift Multiple */
            conversion_lift_multiple: number;
            /** Total Leads Scored */
            total_leads_scored: number;
            /** Hot Leads Count */
            hot_leads_count: number;
            /** Warm Leads Count */
            warm_leads_count: number;
            /** Cold Leads Count */
            cold_leads_count: number;
            /** Thin File Customers Scored */
            thin_file_customers_scored: number;
            /** Thin File Coverage Pct */
            thin_file_coverage_pct: number;
            /** Avg Repayment Capacity Score */
            avg_repayment_capacity_score: number;
            /** Model Precision */
            model_precision: number;
            /** Model Recall */
            model_recall: number;
            /** Model F1 */
            model_f1: number;
        };
        /** SimulateInput */
        SimulateInput: {
            /** Monthly Income */
            monthly_income: number;
            /**
             * Income Type
             * @enum {string}
             */
            income_type: "Salaried" | "Self-Employed" | "Business";
            /** Existing Emi */
            existing_emi: number;
            /** Recent Calculator Visits */
            recent_calculator_visits: number;
        };
        /** TopFactor */
        TopFactor: {
            /** Factor */
            factor: string;
            /**
             * Impact
             * @enum {string}
             */
            impact: "positive" | "negative";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_leads_leads_get: {
        parameters: {
            query?: {
                /** @description Filter by tier (e.g., Hot, Warm, Cold) */
                tier?: string | null;
                /** @description Filter by recommended product */
                product?: string | null;
                /** @description Filter by thin file status */
                thin_file?: boolean | null;
                /** @description Pagination skip */
                skip?: number;
                /** @description Pagination limit */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_leads__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
        };
    };
    simulate_lead_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
